fix version to 29.1 and better melpazoid

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -66,6 +66,12 @@ jobs:
           if grep -q ': error: ' output.log ; then
             echo "Error detected, failing workflow" ; exit 1
           fi
+          if grep -q ' with [melpazoid]' output.log ; then
+            echo "Melpazoid warning detected, failing workflow" ; exit 1
+          fi
+          if grep -q ' with package-lint ' output.log ; then
+            echo "Checkdoc warning detected, failing workflow" ; exit 1
+          fi
           if grep -q ' with checkdoc ' output.log ; then
             echo "Checkdoc warning detected, failing workflow" ; exit 1
           fi
