configure melpazoid

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -34,11 +34,18 @@ jobs:
         run: |
           echo $GITHUB_REF
           if make -C ~/melpazoid |& tee output.log; then
-            :
-            # if grep -q "Warning" output.log; then
+            # if grep -v 'Warning: argument `_' output.log | grep -q "Warning"; then
             #   echo "Warnings detected, failing workflow"
             #   exit 1
             # fi
+            if grep -q "Warning" output.log ; then
+              echo "Warnings detected, failing workflow"
+              exit 1
+            fi
+            if grep -q ': error: ' output.log ; then
+              echo "Error detected, failing workflow"
+              exit 1
+            fi
           else
             echo "Make command failed, failing workflow"
             exit 1
