fix melpazoid warnings

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -34,6 +34,7 @@ jobs:
         run: |
           echo $GITHUB_REF
           if make -C ~/melpazoid |& tee output.log; then
+            [ $? -ne 0 ] && { echo "Error detected, failing workflow"; exit 1; }
             # if grep -v 'Warning: argument `_' output.log | grep -q "Warning"; then
             #   echo "Warnings detected, failing workflow"
             #   exit 1
